version: '3.5'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=food_delivery
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    networks:
      - my-network
  backend:
    image: fullstack-open-flask
    build:
      context: .
      dockerfile: backend.Dockerfile
    restart: on-failure
    depends_on:
      - db
    networks:
      - my-network
  frontend:
    image: fullstack-open-react
    build:
      context: .
      dockerfile: frontend.Dockerfile
    depends_on:
      - backend
    networks:
      - my-network

  proxy:
    image: nginx
    depends_on:
      - frontend
      - backend
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my-network
    ports:
      - 80:80

networks:
  my-network:
